### ISSUE TITLE
GCP KMS for seal/unseal

### ISSUE THREAD

**Issue by aaktaev** [banzaicloud/banzai-charts#725]
I'm using vault chart banzai cloud.And configured seal and unseal to use gcp kms. But getting error in vault-configurer:

time="2019-03-28T17:10:09Z" level=info msg="New config file change vault-config.yml"
time="2019-03-28T17:10:09Z" level=info msg="checking if vault is sealed..."
time="2019-03-28T17:10:09Z" level=info msg="vault is sealed, waiting 30s before trying again..."
time="2019-03-28T17:10:39Z" level=info msg="checking if vault is sealed..."
time="2019-03-28T17:10:39Z" level=info msg="checking if vault is active..."
time="2019-03-28T17:10:39Z" level=info msg="vault is unsealed and active, configuring..."
time="2019-03-28T17:10:39Z" level=error msg="error configuring vault: unable to get key 'vault-root': error getting object for key 'vault-root': storage: object doesn't exist"

**Comment by aaktaev** [comment]
```
seal:
      gcpckms:
        credentials: "/etc/gcp/service-account.json"
        project: "gke-cluster-222716"
        region: "global"
        key_ring: "gke-cluster"
        crypto_key: "gke-cluster"
```

and 

```
unsealer:
  image:
    repository: banzaicloud/bank-vaults
    tag: 0.4.13
    pullPolicy: IfNotPresent
  args: [
      "--mode",
      "google-cloud-kms-gcs",
      "--google-cloud-kms-crypto-key",
      "gke-cluster" ,
      "--google-cloud-kms-key-ring",
      "gke-cluster",
      "--google-cloud-kms-location",
      "global",
      "--google-cloud-kms-project",
      "gke-cluster-222716",
      "--google-cloud-storage-bucket",
      "2021-infra",
      "--secret-shares",
      "5",
      "--secret-threshold",
      "3"
  ]

```
Service account has all permissions (storage admin, kms admin)

**Comment by aaktaev** [comment]
Did deployment from master, here is my values.yaml:

```

# Default values for vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
strategy:
  type: RollingUpdate
image:
  repository: vault
  tag: 1.1.0
  pullPolicy: IfNotPresent
service:
  name: vault
  type: NodePort
  port: 8200
  # annotations:
  #   cloud.google.com/load-balancer-type: "Internal"

ingress:
  enabled: false
  # Used to create Ingress record (should used with service.type: ClusterIP).
  # hosts:
  #  - chart-example.local
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: "true"
  # tls:
  #   Secrets must be manually created in the namespace.
  #   - secretName: chart-example-tls
  #     hosts:
  #       - chart-example.local
persistence:
  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  enabled: false
  ## Vault data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ## set, choosing the default provisioner. (gp2 on AWS, standard on
  ## GKE, AWS & OpenStack)
  # storageClass: "-"
  # Used for hostPath persistence if left empty, "emptyDir" will be used
  hostPath: ""
  ## Set default PVC size
  size: 10G
  ## Set default PVC access mode: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessMode: ReadWriteOnce
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "9102"
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
vault:
  # Allows the mounting of various custom secrets to enable production vault
  # configurations. The comments show an example usage for mounting a TLS
  # secret. The two fields required are a secretName indicating the name of
  # the Kuberentes secret (created outside of this chart), and the mountPath
  # at which it should be mounted in the Vault container.
  customSecrets:
    - secretName: gcp-sa
      mountPath: /etc/gcp

    # - secretName: vault-tls
    #   mountPath: /vault/tls
  externalConfig:
    # Allows creating policies in Vault which can be used later on in roles
    # for the Kubernetes based authentication.
    # See https://www.vaultproject.io/docs/concepts/policies.html for more information.
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }
    auth:
      - type: kubernetes
        # Allows creating roles in Vault which can be used later on for the Kubernetes based
        # authentication.
        # See https://www.vaultproject.io/docs/auth/kubernetes.html#creating-a-role for
        # more information.
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h
    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
  config:
    # A YAML representation of a final vault config.json file.
    # See https://www.vaultproject.io/docs/configuration/ for more information.
    listener:
      tcp:
        address: '[::]:8200'
        tls_disable: true
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key

    telemetry:
      statsd_address: localhost:9125

    ui: true

    seal:
      gcpckms:
        credentials: "/etc/gcp/service-account.json"
        project: "gke-cluster-222716"
        region: "global"
        key_ring: "gke-cluster"
        crypto_key: "gke-cluster"


    # See https://www.vaultproject.io/docs/configuration/storage/ for storage backends
    storage:
      gcs:
        bucket: "2021-infra"
        credentials_file: "/etc/gcp/service-account.json"
        ha_enabled: "true"
    api_addr: https://vault.2021.services:8200

      # file:
      #   path: "/vault/file"
      # consul:
      #   address: ""
      #   path: ""
      #
      # etcd:
      #   address: ""
      #   path: "vault/"
      #
      # s3:
      #   bucket: ""
      #   region: ""
      #   access_key: ""
      #   secret_key: ""
      #   endpoint: "" # When not using AWS S3
      #
      # gcs:
      #   bucket: ""
      #   credentials_file: ""
      #   ha_enabled: "true"
    # api_addr: http://localhost:8200

  # Until this issue is fixed: https://github.com/kubernetes/helm/issues/3117
  # we have to workaround the default storage problem.
  #defaultStorage:
          #storage:
            #file:
              #        path: "/vault/file"

  logLevel: info

unsealer:
  image:
    repository: banzaicloud/bank-vaults
    tag: 0.4.13
    pullPolicy: IfNotPresent
  args: [
      "--mode",
      "google-cloud-kms-gcs",
      "--google-cloud-kms-crypto-key",
      "gke-cluster" ,
      "--google-cloud-kms-key-ring",
      "gke-cluster",
      "--google-cloud-kms-location",
      "global",
      "--google-cloud-kms-project",
      "gke-cluster-222716",
      "--google-cloud-storage-bucket",
      "2021-infra",
      "--secret-shares",
      "5",
      "--secret-threshold",
      "3"
  ]
  metrics:
    enabled: true
    debug: true
    name: metrics
    type: ClusterIP
    port: 9091
    serviceMonitor:
      enabled: false
      additionalLabels: {}
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "9091"

statsd:
  metrics:
    enabled: true
    port: 9102
    serviceMonitor:
      enabled: false
      additionalLabels: {}
  config:
    mappings:
    - match: vault.route.*.*
      name: "vault_route"
      labels:
        method: "$1"
        path: "$2"
```

**Comment by aaktaev** [comment]
On gcp storage bucket it creates two folder: `core` and `sys` .

**Comment by kozmagabor** [comment]
Hi @aaktaev ,

The `vault configurer` and `unsealer` container didn't get the GCP secret.

I fixed it in #726 and put a simple example into the chart readme. Please check it.

Regards,
Gabo

**Comment by aaktaev** [comment]
Hi, @kozmagabor ,
still getting error:
time="2019-04-01T08:58:44Z" level=error msg="error configuring vault: unable to get key 'vault-root': error getting object for key 'vault-root': storage: object doesn't exist"

**Comment by aaktaev** [comment]
```
Containers:
  vault:
    Container ID:  docker://f3743f97ea510d6e204ac72ee49e45622059ac6141cc2d769d1fd98c998bc003
    Image:         vault:1.1.0
    Image ID:      docker-pullable://vault@sha256:b2871c8ab8479471ae3a965d5f089b2729628025449d1c0a17141510bbb446a0
    Ports:         8200/TCP, 8201/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      vault
      server
      -config
      /vault/config/config.json
    State:          Running
      Started:      Mon, 01 Apr 2019 11:58:08 +0300
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:      100m
    Liveness:   http-get http://:vault/v1/sys/init delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:vault/v1/sys/health%3Fstandbyok&perfstandbyok delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      gcp-sa  Secret  Optional: false
    Environment:
      VAULT_CACERT:     /vault/tls/ca.crt
      VAULT_LOG_LEVEL:  info
      VAULT_ADDR:       http://127.0.0.1:8200
    Mounts:
      /etc/gcp from gcp-sa (rw)
      /root/ from vault-root (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from vault-token-jgz97 (ro)
      /vault/config/ from vault-config (rw)
      /vault/file from vault-file (rw)
      /vault/tls from vault-tls (rw)
  vault-unsealer:
    Container ID:  docker://e10ea6d8b6c1bf0275b08d3d3c09e55bc50d6188d4ac093d2f9683e462427632
    Image:         banzaicloud/bank-vaults:0.4.13
    Image ID:      docker-pullable://banzaicloud/bank-vaults@sha256:dd5f3417909bf79434d5ffd94972353fd377e63785017e16568705721cab3148
    Port:          9091/TCP
    Host Port:     0/TCP
    Command:
      bank-vaults
      unseal
      --init
    Args:
      --mode
      google-cloud-kms-gcs
      --google-cloud-kms-crypto-key
      kms1
      --google-cloud-kms-key-ring
      kms1
      --google-cloud-kms-location
      eur4
      --google-cloud-kms-project
      gke-cluster-222716
      --google-cloud-storage-bucket
      2021-infra
      --secret-shares
      5
      --secret-threshold
      3
    State:          Running
      Started:      Mon, 01 Apr 2019 11:58:18 +0300
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 01 Apr 2019 11:58:13 +0300
      Finished:     Mon, 01 Apr 2019 11:58:17 +0300
    Ready:          True
    Restart Count:  1
    Requests:
      cpu:  100m
    Environment Variables from:
      gcp-sa  Secret  Optional: false
    Environment:
      VAULT_CACERT:  /vault/tls/ca.crt
      VAULT_ADDR:    http://127.0.0.1:8200
    Mounts:
      /etc/gcp from gcp-sa (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from vault-token-jgz97 (ro)
      /vault/tls from vault-tls (rw)
  vault-configurer:
    Container ID:  docker://0d058a7f3341133e40ad3daf272782023270841b6929ed67283ec79f2014f438
    Image:         banzaicloud/bank-vaults:0.4.13
    Image ID:      docker-pullable://banzaicloud/bank-vaults@sha256:dd5f3417909bf79434d5ffd94972353fd377e63785017e16568705721cab3148
    Port:          <none>
    Host Port:     <none>
    Command:
      bank-vaults
      configure
    Args:
      --mode
      google-cloud-kms-gcs
      --google-cloud-kms-crypto-key
      kms1
      --google-cloud-kms-key-ring
      kms1
      --google-cloud-kms-location
      eur4
      --google-cloud-kms-project
      gke-cluster-222716
      --google-cloud-storage-bucket
      2021-infra
      --secret-shares
      5
      --secret-threshold
      3
    State:          Running
      Started:      Mon, 01 Apr 2019 11:58:13 +0300
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:  100m
    Environment Variables from:
      gcp-sa  Secret  Optional: false
    Environment:
      VAULT_CACERT:  /vault/tls/ca.crt
      VAULT_ADDR:    http://127.0.0.1:8200
    Mounts:
      /config/ from vault-config (rw)
      /etc/gcp from gcp-sa (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from vault-token-jgz97 (ro)
      /vault/tls from vault-tls (rw)
  prometheus-statsd-exporter:
    Container ID:  docker://8281c134bfa4aa501f64bbba5faca345969f87cdf5ee6b6bb75eb015f6b5d62b
    Image:         prom/statsd-exporter:latest
    Image ID:      docker-pullable://prom/statsd-exporter@sha256:d929b9fc451cedfe7738aeb66e07e67d022ab1388862bda7b545f88b26c2c38b
    Port:          9102/TCP
    Host Port:     0/TCP
    Args:
      --statsd.mapping-config=/tmp/statsd-mapping.conf
    State:          Running
      Started:      Mon, 01 Apr 2019 11:58:14 +0300
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /tmp/ from statsd-mapping (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from vault-token-jgz97 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  vault-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vault-config
    Optional:    false
  vault-root:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  vault-file:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  gcp-sa:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  gcp-sa
    Optional:    false
  vault-tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vault-tls
    Optional:    false
  statsd-mapping:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      vault-statsd-mapping
    Optional:  false
  vault-token-jgz97:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vault-token-jgz97
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
```

**Comment by bonifaido** [comment]
Hi @aaktaev,

I think in this case your Vault has been initialized by Vault itself since you are using auto unseal and bank-vaults unseal as well:

```yaml
seal:
  gcpckms:
    credentials: "/etc/gcp/service-account.json"
    project: "gke-cluster-222716"
    region: "global"
    key_ring: "gke-cluster"
    crypto_key: "gke-cluster"
```

I think this `seal` block has to be removed from your config entirely vanish all data from the storage backend and start installing again.

**Comment by jozuenoon** [comment]
If I can have an suggestion here:

- obviously Vault has been already initialized and for some reason vault-root key has been lost so you need to delete `sys` and `core` folders before you precede,
- since vault initialization is done during `initContainer` step AFAIK it was very hard to spot logs either using `kubectl logs` or `stackdriver` (I'm having clusters on GCP). But you should specifically target those logs to see why `vault-root` key is not created. In my case if I recall properly this was related to permissions problem.
- as suggested above you should use one method to handle unsealing. Naming is a bit misleading I agree. There are two options which are mutually exclusive which is not obvious from configuration. One is recently added, originating from Vault itself and other is using `banzaicloud`'s tool to handle vault in general including unsealing. I decided to use the latter one which is described under `unsealer` section and I completely dropped `seal` section from vault configuration.

And that worked for me. I was having exactly same symptoms. Good luck!

**Comment by bonifaido** [comment]
Thanks @jozuenoon 
A preflightCheck  feature has been added to Bank-Vaults in the meantime, so this issue shouldn't happen anymore, please check the latest version.
