### ISSUE TITLE
Unable to install vault cluster using banzaicloud vault-operator helm chart

### ISSUE THREAD

**Issue by robertgates55** [banzaicloud/banzai-charts#852]
Am having trouble following/finding documentation on which charts to deploy in what order. Not sure if this is the right place to report this, but any advice where is would be appreciated!

*What I have*: an EKS cluster, with RBAC enabled, k8s 1.12
*What I'd like*: to install Vault, backed by an HA etcd cluster, (ideally then with auto-unsealing using kms, but baby steps...)
*What I've tried so far*:
1. Installed the banzai-charts vault-operator chart:
```
helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
helm upgrade --install vault-operator banzaicloud-stable/vault-operator \
--version=0.4.15 \
--set=etcd-operator.enabled=true \
--set=etcd-operator.etcdOperator.commandArgs.cluster-wide=true
```
This all goes green and looks happy. I can see the vault-operator; and I can also see the etcd-operator has been deployed alongside it as expected.

2. Deployed the example deploy file (and rbac) for cr-etcd-ha:
```
 kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/cr-etcd-ha.yaml
```

3. In the `vault-operator` logs, I then get the following error:
```
{"level":"info","ts":1560001172.2495298,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"default","Request.Name":"vault"}
{"level":"error","ts":1560001178.9499567,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"vault-controller","request":"default/vault","error":"failed to create/update etcd cluster: no matches for kind \"EtcdCluster\" in version \"etcd.database.coreos.com/v1beta2\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:88"}
```

So it's (as hoped) trying to create an etdc cluster for the requested vault cluster, but failing. Since I can see that the EtcdCluster kind is installed (`kubectl api-resources -o wide | grep EtcdCluster`), I'm guessing I have an RBAC issue, but I've been struggling to work out where.

Is there any more documentation I've missed that links together the banzaicloud vault-operator charts with the bank-vaults examples? What am I doing wrong?

**Comment by robertgates55** [comment]
As an additional, alternative answer, I've successfully deployed the following (which deploys a 0.9.13 etcd-operator, rather than 0.9.11)

```
kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/operator-rbac.yaml
 kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/operator.yaml

 kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/etcd-rbac.yaml
 kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/etcd-operator.yaml

 kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/rbac.yaml
 kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/cr-etcd-ha.yaml
```

This *does* work. Which I _think_ does point to an issue with this helm chart?

**Comment by bonifaido** [comment]
Hi @robertgates55, thanks for reporting this, to be honest, I have never seen this error. After some investigation, I found that this is a timing issue between the registration of the EtcdCluster resource type and the startup of the Vault operator (and the priming of its cache). If I restart the vault-operator Pod after the etcd-operator has successfully started up and has registered the EtcdCluster type everything works as expected. I'm thinkg about a fix now.

**Comment by bonifaido** [comment]
A fix has been pushed for review: https://github.com/banzaicloud/banzai-charts/pull/853

**Comment by bonifaido** [comment]
The fix has been released, the new chart version is 0.2.14.

**Comment by robertgates55** [comment]
Thanks for the super quick response.

Sadly still having problems - the new init container is throwing:
```
Error from server (Forbidden): customresourcedefinitions.apiextensions.k8s.io "etcdclusters.etcd.database.coreos.com" is forbidden: User "system:serviceaccount:default:vault-operator" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

So I'd guess we'll need to modify the rbac template too.

**Comment by bonifaido** [comment]
Sorry, somehow I left this out, fix of the fix is on the way.

**Comment by bonifaido** [comment]
@robertgates55 please try 0.2.15

**Comment by robertgates55** [comment]
Yep - all good. 

THANKS!

**Comment by matyix** [comment]
@robertgates55 thanks for reporting this and sorry for the inconvenience; again, we appreciate the (double) testing.

**Comment by robertgates55** [comment]
Thanks.

Without wanting to raise a new ticket just for this - is there a recommended `vault` helm chart to use with this `vault-operator`? It looks to me like the `vault` chart in this repo overlaps with this operator rather than works alongside it?

**Comment by bonifaido** [comment]
The operator is the suggested way to run Vault, however some people don't like to use the operator and would like to run their application in its bare form, we also support this way, but it's features are more limited.
